repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json

  - repo: https://github.com/rubocop/rubocop
    rev: v1.61.2  
    hooks:
      - id: rubocop
        args: [--parallel]

  - repo: https://github.com/sds/haml-lint
    rev: v0.50.0
    hooks:
      - id: haml-lint

  - repo: https://github.com/brigade/overcommit
    rev: v0.60.0
    hooks:
      - id: overcommit

  - repo: local
    hooks:
      - id: bundle-install
        name: Bundle Install Check
        entry: bundle check || bundle install
        language: system
        always_run: true